services:
  fenecon-crawler:
    container_name: fenecon-crawler
    image: ghcr.io/dieechtenilente/fenecon-influx-exporter/fenecon-influx-exporter:250226feb
    restart: unless-stopped
    environment:
      - FENECON_IP=1.2.3.4
      - INFLUXDB_SERVER=influxdb2.local
      - INFLUXDB_TOKEN=aaasecrettoken==
      - INFLUXDB_ORG=org
      - INFLUXDB_BUCKET=bucket