name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Docker registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/fenecon-influx-exporter:$(date +'%y%m%d%h') .

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/fenecon-influx-exporter:$(date +'%y%m%d%h')